# name: Node.js CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           # cache: 'npm'
#       - name: 🔨 Build Project
#         run: |
#           cd app
#           npm install
#           npm run build

#       - name: 📂 Sync files
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#         with:
#           local-dir: ./app/dist/
#           server: ${{ secrets.FTP_SERVER_FRONT }}
#           username: ${{ secrets.FTP_USERNAME_FRONT }}
#           password: ${{ secrets.FTP_PASSWORD_FRONT }}

# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: 🔨 Build Project
      - run: cd app
      - run: npm install
      - run: npm run build
      - name: 📂 Sync files
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      - with:
          local-dir: ./app/dist/
          server: ${{ secrets.FTP_SERVER_FRONT }}
          username: ${{ secrets.FTP_USERNAME_FRONT }}
          password: ${{ secrets.FTP_PASSWORD_FRONT }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
